testEnvironment:
    MCloud:
        baseUrl: 'http://mcloud.matrium.com.au:7100/api/v1'
    Login:
        User: 'Peter.Zhang@matrium.com.au'
        accessToken: 'Bearer 5da9a2eb965040cbada4e0b22440ac0eee4e666e02264e36bbc41dfffa271fba'
    MAndroid2AgentPath: 'c:/tmp/MatriumMAndroid2-release.jar'
    testUsers:
        MO:
            serial: 'R5CN7187TJH'
            MSISDN: '+61402537622'
        MT:
            serial: 'R5CN30MJ2DJ'
            MSISDN: '+61431202671'




