testEnvironment:
    Harbor:
        baseUrl: '192.168.100.121/api/v2.0'
        Login:
            User: 'admin'
            Password: 'Matrium123'
        ProjectName: 'landslide'
        RepositoryName: 'landslide'
    ImagePath: 'c:/tmp/Landslide_19.8_Docker_Container.tar.gz'



